
spring.application.name=cardio

# Configuración de la Base de Datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:cardiodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=8889

# Habilitar la consola web de H2 para ver las tablas en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de JPA / Hibernate
# "update" creará las tablas automáticamente en base a nuestro código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true